function s = get_s(t)
%GET_S
%    S = GET_S(T)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    10-Jul-2025 20:05:52

t2 = ((0.0 < t) & (t <= 1.0e+1));
t3 = ((1.0e+1 < t) & (t <= 3.0e+1));
t4 = ((3.0e+1 < t) & (t <= 4.0e+1));
t5 = t.^2;
t6 = t5./6.0e+2;
if ~all(cellfun(@isscalar,{t,t2,t3,t4}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t2)
    s = t6;
elseif (t3)
    s = t./3.0e+1-1.0./6.0;
elseif (t4)
    s = t.*(2.0./1.5e+1)-t6-5.0./3.0;
elseif (t == 3.0e+1)
    s = 5.0./6.0;
elseif (t <= 0.0)
    s = 0.0;
elseif (4.0e+1 <= t)
    s = 1.0;
else
    s = NaN;
end
end
